const constants = {
  FRAMERATE: 60,
  DEFAULT_HEIGHT: 510,
  DEFAULT_WIDTH: 900,
  TOUCH_INPUT: navigator.userAgent.match(/(iPhone|iPad|iPod|Android)/i),

  ENEMY_COUNT: 2,
  ENEMY_SIZE: 10,
  ENEMY_TYPE_NORMAL: 1,
  ENEMY_TYPE_BOMB: 2,
  // ENEMY_TYPE_NORMAL_MOVER: 3,
  // ENEMY_TYPE_BOMB_MOVER: 4,
  // ENEMY_MOVER_START_FRAME: this.FRAMERATE * 2,

  SCORE_PER_ENEMY: 30,
  SCORE_PER_TICK: 0.01,
  ENERGY_PER_ENEMY_DEATH: -30,
  ENERGY_PER_ENEMY_ENCLOSED: 1,
  ENERGY_PER_BOMB_ENCLOSED: -30,
  MULTIPLIER_LIMIT: 4,

  HEADER_HEIGHT: 30,
  MENU_FADE_IN_DURATION:600,
  MENU_FADE_OUT_DURATION: 600,

  STATE_WELCOME: 'start',
  STATE_PLAYING: 'playing',
  STATE_LOSER: 'loser',
  STATE_WINNER: 'winner'
};

// constants.ENEMY_MOVER_START_FRAME = constants.FRAMERATE * 2;

// console.log(constants);
export default constants;