const constants = {
  FRAMERATE: 60,
  DEFAULT_HEIGHT: 510,
  DEFAULT_WIDTH: 900,
  TOUCH_INPUT: navigator.userAgent.match(/(iPhone|iPad|iPod|Android)/i),

  ENEMY_COUNT: 2,
  ENEMY_SIZE: 10,
  ENEMY_TYPE_NORMAL: 1,
  ENEMY_TYPE_BOMB: 2,

  SCORE_PER_ENEMY: 30,
  SCORE_PER_TICK: 0.02,
  ENERGY_PER_ENEMY_DEATH: -20,
  ENERGY_PER_ENEMY_ENCLOSED: 1,
  ENERGY_PER_BOMB_ENCLOSED: -30,
  MULTIPLIER_LIMIT: 5,

  HEADER_HEIGHT: 30
};

export default constants;